version: 2.1
jobs:
  # Manually running docker with --privileged flag.
  gen_iso:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Download docker image
          shell: /bin/sh
          command: |
            docker pull ghcr.io/void-linux/void-linux:latest-full-x86_64
      - run:
          name: Generate ISO
          shell: /bin/sh
          command: |
            docker run --privileged -v $PWD:/root/project -v /dev:/dev -it ghcr.io/void-linux/void-linux:latest-full-x86_64 /bin/sh -c "\
              chmod +x /root/project/ci/set_repository.sh && \
              /root/project/ci/set_repository.sh && \
              chmod +x /root/project/ci/install_dependencies.sh && \
              /root/project/ci/install_dependencies.sh && \
              chmod +x /root/project/gen.sh && \
              /root/project/gen.sh && \
              sh -c 'mv -v /root/void-mklive/void-live-x86_64-*.iso /root/project/void-live-x86_64-<< pipeline.git.revision >>.iso' \
            "
      - store_artifacts:
          path: ./void-live-x86_64-<< pipeline.git.revision >>.iso

workflows:
  generate_iso:
    jobs:
      - gen_iso
